'use strict';

const LEVELS = [
    { id: 1, name: 'Balloon Pop', icon: '🎈', diff: 'easy', time: 60,
      instruction: 'Click 20 balloons before they disappear!',
      skills: ['singleClick'] },
    { id: 2, name: 'Target Hunter', icon: '🎯', diff: 'easy', time: 55,
      instruction: 'Click moving targets. Avoid red obstacles!',
      skills: ['singleClick'] },
    { id: 3, name: 'Color Match', icon: '🎨', diff: 'easy', time: 50,
      instruction: 'Click only objects matching the target color.',
      skills: ['singleClick'] },
    { id: 4, name: 'Fruit Catcher', icon: '🍎', diff: 'easy', time: 60,
      instruction: 'Drag each fruit into its matching basket.',
      skills: ['dragDrop'] },
    { id: 5, name: 'Object Sorting', icon: '📦', diff: 'easy', time: 60,
      instruction: 'Drag items into the correct category boxes.',
      skills: ['dragDrop'] },
    { id: 6, name: 'Hidden Object Hunt', icon: '🔍', diff: 'medium', time: 70,
      instruction: 'Find and click all hidden objects in the scene.',
      skills: ['singleClick'] },
    { id: 7, name: 'Connect the Dots', icon: '🔗', diff: 'medium', time: 65,
      instruction: 'Click numbered dots in order from 1 to 10.',
      skills: ['singleClick'] },
    { id: 8, name: 'Shape Tracing', icon: '✏️', diff: 'medium', time: 75,
      instruction: 'Trace the circle, square, and triangle accurately.',
      skills: ['tracing'] },
    { id: 9, name: 'Puzzle Builder', icon: '🧩', diff: 'medium', time: 80,
      instruction: 'Drag puzzle pieces to complete the picture.',
      skills: ['dragDrop'] },
    { id: 10, name: 'Maze Runner', icon: '🏃', diff: 'medium', time: 70,
      instruction: 'Move through the maze without touching walls.',
      skills: ['singleClick'] },
    { id: 11, name: 'Path Follower', icon: '🛤️', diff: 'hard', time: 65,
      instruction: 'Follow the narrow path from START to FINISH.',
      skills: ['tracing'] },
    { id: 12, name: 'Memory Click', icon: '🧠', diff: 'hard', time: 60,
      instruction: 'Remember positions, then click the correct objects.',
      skills: ['singleClick'] },
    { id: 13, name: 'Traffic Controller', icon: '🚦', diff: 'hard', time: 55,
      instruction: 'Click traffic lights to let 12 vehicles pass safely.',
      skills: ['singleClick'] },
    { id: 14, name: 'Computer Lab', icon: '💻', diff: 'hard', time: 50,
      instruction: 'Click each computer device when prompted.',
      skills: ['singleClick'] },
    { id: 15, name: 'Mouse Master Tournament', icon: '🏆', diff: 'expert', time: 120,
      instruction: 'Complete all mouse skills in one ultimate challenge!',
      skills: ['singleClick', 'doubleClick', 'dragDrop', 'tracing'] }
];

window.LEVELS = LEVELS;
